#!/bin/bash

set -euo pipefail

# Resets on aborted connections are expected.
socat TCP-LISTEN:8080,bind=127.0.0.1,fork,reuseaddr UNIX-CONNECT:/run/ava/proxy.sock \
	2> >(grep --line-buffered -vE ' E (read|write)\([0-9]+' >&2) &

exec "$@"
